<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rwbfeupload"
 *
 * Auto generated by Extension Builder 2016-06-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RWB Example Usage for EXT media_upload (FE file upload)',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Falk Röder',
	'author_email' => 'mail@falk-roeder.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'media_upload' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);